export const requestType = {
    POST: "post",
    GET: "get",
    PUT: "put",
    DELETE: "delete",
};
export const endPoints = {
    registerUser:"registerUser",
    loginUser:"loginUser",
    sendCode:"sendCode",
    addComplaint:"addComplaint",
    updateComplaintStatus:"updateComplaintStatus",
    getComplaintsByUser:"getComplaintsByUser",
    getComplaintsByService:"getComplaintsByService",
    getComplaintsByService:"getComplaintsByService",
    registerAppartmentAdmin:"registerAppartmentAdmin",
    loginAppartmentAdmin:"loginAppartmentAdmin",
    sendCodeAdmin:"sendCodeAdmin",
    changePasswordUser:"changePasswordUser",
    addUtitlity:"addUtitlity",
    getUtilitiesByUser:"getUtilitiesByUser",
    getUtilitiesByService:"getUtilitiesByService",
    getAllUtilities:"getAllUtilities",
    getComplaintsByAdmin:"getComplaintsByAdmin",
    getAllPendingUsers:"getAllPendingUsers",
    updateUserStatus:"updateUserStatus",
    getAllUsers:"getAllUsers",
    getPendingComplaintsByAdmin:"getPendingComplaintsByAdmin",
    getSolvedComplaintsByAdmin:"getSolvedComplaintsByAdmin",
    getInprogressComplaintsByAdmin:"getInprogressComplaintsByAdmin",
    getUtilitiesByAdmin:"getUtilitiesByAdmin",
    getAllNotifications:"getAllNotifications",
    addNotication:"addNotication",
    changePasswordAdmin:"changePasswordAdmin",
    addPaymentDetails:"addPaymentDetails",
    getAllPaymentDetails:"getAllPaymentDetails",
    updatePaymentDetail:"updatePaymentDetail",
    resetPasswordAdmin:"resetPasswordAdmin",
    sendCodeAdminForget:"sendCodeAdminForget",
    sendCodeForget:"sendCodeForget",
    resetPasswordUser:"resetPasswordUser",
};